#include "xoled.h"
#include "mqtt.h"
#include <PubSubClient.h>
namespace { WiFiClientSecure tls; PubSubClient client(tls); uint32_t retry_at = 0; char mqtt_ip[sizeof(config.printer_ip)]{}, mqtt_serial[sizeof(config.printer_serial)]{}, mqtt_access_code[sizeof(config.access_code)]{};
PrinterState decode_state(const char* state) { if (!state) return PrinterState::Unknown; if (!strcmp(state, "RUNNING")) return PrinterState::Printing; if (!strcmp(state, "PAUSE") || !strcmp(state, "PAUSED")) return PrinterState::Paused; if (!strcmp(state, "FINISH") || !strcmp(state, "FINISHED")) return PrinterState::Finished; if (!strcmp(state, "FAILED") || !strcmp(state, "ERROR")) return PrinterState::Error; if (!strcmp(state, "PREPARE") || !strcmp(state, "PREPARING")) return PrinterState::Preparing; if (!strcmp(state, "IDLE")) return PrinterState::Idle; return PrinterState::Unknown; }
void on_message(char*, byte* payload, unsigned int length) { JsonDocument filter; filter["print"]["gcode_state"] = true; filter["print"]["mc_percent"] = true; filter["print"]["percent"] = true; filter["print"]["layer_num"] = true; filter["print"]["total_layer_num"] = true; filter["print"]["remaining_time"] = true; filter["print"]["subtask_name"] = true; JsonDocument doc; if (deserializeJson(doc, payload, length, DeserializationOption::Filter(filter))) { Serial.println("MQTT-Nutzdaten nicht lesbar"); return; } JsonObjectConst print = doc["print"]; if (print.isNull()) return; const PrinterState next = decode_state(print["gcode_state"] | nullptr); if (next != PrinterState::Unknown) printer.state = next; int value = print["mc_percent"] | (print["percent"] | -1); if (value >= 0 && value <= 100) printer.progress = value; printer.layer = print["layer_num"] | printer.layer; printer.total_layers = print["total_layer_num"] | printer.total_layers; printer.remaining_seconds = (print["remaining_time"] | printer.remaining_seconds) * 60UL; if (print["subtask_name"].is<const char*>()) printer.job_name = (const char*)print["subtask_name"]; if (printer.state == PrinterState::Disconnected && (printer.progress > 0 || printer.job_name.length())) printer.state = PrinterState::Printing; }
}
void mqtt_begin() { tls.setInsecure(); client.setServer(config.printer_ip, 8883); strlcpy(mqtt_ip, config.printer_ip, sizeof(mqtt_ip)); strlcpy(mqtt_serial, config.printer_serial, sizeof(mqtt_serial)); strlcpy(mqtt_access_code, config.access_code, sizeof(mqtt_access_code)); client.setBufferSize(49152); client.setCallback(on_message); }
void mqtt_reconfigure() { if (!strcmp(mqtt_ip, config.printer_ip) && !strcmp(mqtt_serial, config.printer_serial) && !strcmp(mqtt_access_code, config.access_code)) return; client.disconnect(); client.setServer(config.printer_ip, 8883); strlcpy(mqtt_ip, config.printer_ip, sizeof(mqtt_ip)); strlcpy(mqtt_serial, config.printer_serial, sizeof(mqtt_serial)); strlcpy(mqtt_access_code, config.access_code, sizeof(mqtt_access_code)); retry_at = 0; }
bool mqtt_is_connected() { return client.connected(); }
void mqtt_loop() { if (WiFi.status() != WL_CONNECTED) { if (config_has_printer()) printer.state = PrinterState::Disconnected; return; } if (!config_has_printer()) { printer.state = PrinterState::Disconnected; return; } if (!client.connected() && millis() >= retry_at) { retry_at = millis() + 5000; char id[40]; snprintf(id, sizeof(id), "XOLED-%06lx", (unsigned long)(ESP.getEfuseMac() & 0xffffff)); if (client.connect(id, "bblp", config.access_code)) { char topic[80]; snprintf(topic, sizeof(topic), "device/%s/report", config.printer_serial); client.subscribe(topic); Serial.println("MQTT verbunden"); } else { Serial.printf("MQTT getrennt (Code %d)\n", client.state()); } } client.loop(); }
