#include "xoled.h"
#include "webserver.h"
#include "mqtt.h"
#include <ESPAsyncWebServer.h>
#include <AsyncJson.h>
#include <Update.h>
namespace { AsyncWebServer server(80); void send_json(AsyncWebServerRequest* request, JsonDocument& doc, int status = 200) { String out; serializeJson(doc, out); request->send(status, "application/json", out); } void read_form(AsyncWebServerRequest* request, JsonDocument& doc) { for (uint8_t i = 0; i < request->params(); ++i) { const AsyncWebParameter* p = request->getParam(i); if (p->isPost()) doc[p->name()] = p->value(); } if (doc["ip"].is<const char*>()) doc["printer_ip"] = doc["ip"]; if (doc["serial"].is<const char*>()) doc["printer_serial"] = doc["serial"]; if (doc["color_bg"].is<const char*>()) doc["background_color"] = doc["color_bg"]; if (doc["color_fg"].is<const char*>()) doc["progress_color"] = doc["color_fg"]; } void save(AsyncWebServerRequest* request) { JsonDocument body; read_form(request, body); String error; if (!config_update(body.as<JsonObjectConst>(), error)) { JsonDocument reply; reply["error"] = error.length() ? error : "NVS konnte nicht gespeichert werden"; send_json(request, reply, 400); return; } leds_apply_config(); mqtt_reconfigure(); JsonDocument reply; reply["ok"] = true; reply["message"] = "Konfiguration gespeichert"; send_json(request, reply); } }
bool ota_success = false;
void webserver_begin(bool filesystem_ready) {
  server.on("/api/status", HTTP_GET, [](AsyncWebServerRequest* request) { JsonDocument doc; doc["wifi_connected"] = WiFi.status() == WL_CONNECTED; doc["wifi_configured"] = config_has_wifi(); doc["printer_connected"] = mqtt_is_connected(); doc["printer_configured"] = config_has_printer(); doc["printer_state"] = printer_state_name(printer.state); doc["progress"] = printer.progress; doc["layer"] = printer.layer; doc["total_layers"] = printer.total_layers; doc["remaining_seconds"] = printer.remaining_seconds; doc["job_name"] = printer.job_name; doc["firmware"] = "3.0.0"; doc["uptime"] = millis() / 1000; send_json(request, doc); });
  server.on("/api/config", HTTP_GET, [](AsyncWebServerRequest* request) { JsonDocument doc; config_to_json(doc.to<JsonObject>()); send_json(request, doc); }); server.addHandler(new AsyncCallbackJsonWebHandler("/api/config", [](AsyncWebServerRequest* request, JsonVariant& json) { String error; if (!config_update(json.as<JsonObjectConst>(), error)) { JsonDocument reply; reply["error"] = error.length() ? error : "NVS konnte nicht gespeichert werden"; send_json(request, reply, 400); return; } leds_apply_config(); mqtt_reconfigure(); JsonDocument reply; reply["ok"] = true; send_json(request, reply); }));
  server.on("/api/wifi/scan", HTTP_GET, [](AsyncWebServerRequest* request) { const int count = WiFi.scanNetworks(); JsonDocument doc; JsonArray networks = doc["networks"].to<JsonArray>(); for (int i = 0; i < count; ++i) { JsonObject network = networks.add<JsonObject>(); network["ssid"] = WiFi.SSID(i); network["rssi"] = WiFi.RSSI(i); network["secure"] = WiFi.encryptionType(i) != WIFI_AUTH_OPEN; } WiFi.scanDelete(); send_json(request, doc); });
  server.on("/api/restart", HTTP_POST, [](AsyncWebServerRequest* request) { request->send(202, "application/json", "{\"ok\":true}"); delay(150); ESP.restart(); }); server.on("/api/factory-reset", HTTP_POST, [](AsyncWebServerRequest* request) { if (!config_reset()) { request->send(500, "application/json", "{\"ok\":false}"); return; } request->send(202, "application/json", "{\"ok\":true}"); delay(150); ESP.restart(); });
  server.on("/api/ota", HTTP_POST, [](AsyncWebServerRequest* request) { const bool ok = ota_success && !Update.hasError(); request->send(ok ? 202 : 500, "application/json", ok ? "{\"ok\":true}" : "{\"ok\":false,\"error\":\"Firmware-Update fehlgeschlagen\"}"); if (ok) { delay(500); ESP.restart(); } }, [](AsyncWebServerRequest*, String, size_t index, uint8_t* data, size_t len, bool final) { if (!index) ota_success = Update.begin(UPDATE_SIZE_UNKNOWN, U_FLASH); if (!ota_success) return; if (Update.write(data, len) != len) { ota_success = false; Update.printError(Serial); return; } if (final) ota_success = Update.end(true); });
  server.on("/api/printer-test", HTTP_POST, [](AsyncWebServerRequest* request) { mqtt_reconfigure(); request->send(202, "application/json", "{\"ok\":true}"); }); server.on("/api/wifi-test", HTTP_POST, [](AsyncWebServerRequest* request) { wifi_begin(); request->send(202, "application/json", "{\"ok\":true}"); }); server.on("/api/led-test", HTTP_POST, [](AsyncWebServerRequest* request) { leds_test_start(); request->send(202, "application/json", "{\"ok\":true}"); });
  server.on("/status.json", HTTP_GET, [](AsyncWebServerRequest* request) { request->redirect("/api/status"); }); server.on("/settings.json", HTTP_GET, [](AsyncWebServerRequest* request) { JsonDocument doc; config_to_json(doc.to<JsonObject>(), true); doc["mqtt_server"] = config.printer_ip; doc["mqtt_device_serial"] = config.printer_serial; doc["mqtt_pass"] = config.access_code; send_json(request, doc); }); server.on("/colors.json", HTTP_GET, [](AsyncWebServerRequest* request) { JsonDocument doc; config_to_json(doc.to<JsonObject>()); doc["color_bg"] = doc["background_color"]; doc["color_fg"] = doc["progress_color"]; send_json(request, doc); });
  server.on("/save_wifi", HTTP_POST, save); server.on("/save_printer", HTTP_POST, save); server.on("/save_led", HTTP_POST, save); server.on("/save_colors", HTTP_POST, save);
  if (filesystem_ready) server.serveStatic("/", LittleFS, "/").setDefaultFile("index.html"); else server.on("/", HTTP_GET, [](AsyncWebServerRequest* request) { request->send(503, "text/plain", "LittleFS nicht verfuegbar"); }); server.onNotFound([](AsyncWebServerRequest* request) { request->send(404, "text/plain", "Nicht gefunden"); }); server.begin(); Serial.println("Webserver gestartet");
}
