#include "xoled.h"
#include "mqtt.h"
#include "webserver.h"
#include "improv.h"
PrinterStatus printer;
CRGB* leds = nullptr;
namespace { bool wifi_started = false; uint32_t wifi_retry_at = 0, led_test_until = 0, boot_animation_started = 0; }
const char* printer_state_name(PrinterState state) { switch (state) { case PrinterState::Idle: return "Bereit"; case PrinterState::Preparing: return "Vorbereitung"; case PrinterState::Printing: return "Druckt"; case PrinterState::Paused: return "Pausiert"; case PrinterState::Finished: return "Fertig"; case PrinterState::Error: return "Fehler"; case PrinterState::Disconnected: return "Getrennt"; default: return "Unbekannt"; } }
bool wifi_is_configured() { return config_has_wifi(); }
void wifi_begin() { WiFi.mode(config_has_wifi() ? WIFI_STA : WIFI_AP); if (!config_has_wifi()) { WiFi.softAP("XOLED-Setup"); Serial.println("Offenes Setup-WLAN: XOLED-Setup, WebUI: 192.168.4.1"); return; } WiFi.begin(config.wifi_ssid, config.wifi_pass); wifi_started = true; wifi_retry_at = millis() + 15000; Serial.println("WLAN-Verbindung wird aufgebaut"); }
void wifi_loop() { if (!config_has_wifi() || WiFi.status() == WL_CONNECTED) return; if (!wifi_started || millis() >= wifi_retry_at) { WiFi.disconnect(); WiFi.begin(config.wifi_ssid, config.wifi_pass); wifi_started = true; wifi_retry_at = millis() + 15000; Serial.println("WLAN-Verbindung wird erneut versucht"); } }
void leds_apply_config() { if (!leds) return; FastLED.setBrightness(config.brightness); FastLED.setMaxPowerInMilliWatts(config.max_milliwatts); FastLED.setDither(0); }
void leds_begin() { delete[] leds; leds = new CRGB[config.led_count]; FastLED.addLeds<WS2812B, DATA_PIN, GRB>(leds, config.led_count); leds_apply_config(); boot_animation_started = millis(); FastLED.clear(true); }
void leds_test_start() { led_test_until = millis() + 9000; }
void leds_render() { if (!leds) return; const uint32_t now = millis(), boot_step = (now - boot_animation_started) / 120; if (boot_step < config.led_count) { for (uint16_t i = 0; i < config.led_count; ++i) leds[i] = i <= boot_step ? CRGB::Yellow : CRGB::Black; FastLED.show(); return; } if (now < led_test_until) { const CRGB color[] = {CRGB::Red, CRGB::Green, CRGB::Blue}; fill_solid(leds, config.led_count, color[(now / 1000) % 3]); FastLED.show(); return; } CRGB bg(config.background_color[0], config.background_color[1], config.background_color[2]); CRGB fg(config.progress_color[0], config.progress_color[1], config.progress_color[2]); for (uint16_t i = 0; i < config.led_count; ++i) { switch (printer.state) { case PrinterState::Printing: leds[i] = i < (config.led_count * printer.progress + 99) / 100 ? fg : bg; break; case PrinterState::Finished: leds[i] = (now / 400 + i) % 2 ? fg : CRGB::Black; break; case PrinterState::Error: leds[i] = (now / 300) % 2 ? CRGB::Red : CRGB::Black; break; case PrinterState::Preparing: leds[i] = i == (now / 120) % config.led_count ? CRGB::Orange : bg; break; case PrinterState::Paused: leds[i] = CRGB::Yellow; break; default: leds[i] = bg; break; } } FastLED.show(); }
void setup() { Serial.begin(115200); delay(200); Serial.println("XOLED 3.0 startet"); WiFi.onEvent([](WiFiEvent_t event, WiFiEventInfo_t) { if (event == ARDUINO_EVENT_WIFI_STA_GOT_IP) Serial.printf("WLAN verbunden, WebUI: http://%s\n", WiFi.localIP().toString().c_str()); }); config_load(); leds_begin(); const bool fs_ready = LittleFS.begin(false); if (!fs_ready) Serial.println("LittleFS nicht verfuegbar; Weboberflaeche deaktiviert"); improv_setup(); wifi_begin(); delay(100); webserver_begin(fs_ready); mqtt_begin(); if (!config_has_wifi()) Serial.println("WLAN nicht konfiguriert; Setup-WLAN aktiv"); if (!config_has_printer()) Serial.println("Drucker nicht konfiguriert"); }
void loop() { wifi_loop(); improv_loop(); mqtt_loop(); leds_render(); delay(10); }
